# -*- coding: utf-8 -*-
"""HDP_webapp.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1roid5F1-fzLHwmLxOFPdazTGBp5vjoqQ
"""

import streamlit as st
import numpy as np
import pickle

loaded_model=pickle.load(open('E:\st_project/trained_model.sav','rb'))

def HDP_Prediction(input_data):

   input_data=(33,0,0,1,14,61,0,0,30,1,25,1,2,2)
   #change input data to munpy array
   input_data_as_numpy_array=np.asarray(input_data)
   #reshape 
   input_data_reshape=input_data_as_numpy_array.reshape(1,-1)
   #predict
   prediction=loaded_model.predict(input_data_reshape)
   print(prediction)
   if(prediction[0]==0):

      print("Person do not have a heart disease")
   else:
      print("Person have a heart disease .")

def main():
    
  #title
  st.title('Heart Disease Prediction System')
  
  age=st.text_input('What is your age')
  sex=st.text_input('Enter your sex')
  dataset=st.text_input('Enter your dataset')
  cp=st.text_input('Enter your cp type')
  trestbps=st.text_input('Enter your trestbps')
  chol=st.text_input('Enter your cholestrol')
  fbs=st.text_input('Enter your fbs')
  restecg=st.text_input('Enter your restecg')
  thalch=st.text_input('Enter your thalch')
  exang=st.text_input('Enter your exang')
  oldpeak=st.text_input('Enter your oldpeak')
  slope=st.text_input('Enter your slope')
  ca=st.text_input('Enter your ca')
  thal=st.text_input('Enter your thal')

  diagnosed_result=''

  if st.button("Heart Disease Diagnosis Result"):
      
    
     diagnosed_result=HDP_Prediction(age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal)

  st.success(diagnosed_result)

if __name__ == '__main__':
  main()

